### ISSUE TITLE
on IOS  Library Not Working

### ISSUE THREAD

**Issue by arjundalal** [prscX/react-native-photo-editor#103]
Hello Team,
when we implement this library on IOS react native it will not work properly.
but the same will work on Android.
please help me to solve this issue.

**Comment by prscX** [comment]
@arjundalal: Could you please share details about the issue you are facing.

Thanks
< / Pranav >

**Comment by arjundalal** [comment]
When we open any image for editing than the imgae dose not open in IOS.
It only give popup and close it.

**Comment by prscX** [comment]
Could you please share RN and Library version which you are using.

**Comment by prscX** [comment]
Please make sure that image exist in your apps sandbox. Third part image sharing is not supported.

**Comment by arjundalal** [comment]
Hello Team,
 actually the scenario is that, we get an array of image , when i click on particular image we store that image into local storage and pass the path of local storage.
these all things are working properly on Android.
but when we perform same task on IOS the editor page will open and close automatically. 

My React Version is 0.61.5 
we uses firebase , social login library. etc
my react-native-photo-editor library version is 1.0.3.
and my pod file contain following data. 

//======POD FILE DATA============

platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'Colormycreations' do
  # Pods for Colormycreations
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNSketchCanvas', :path => '../node_modules/@terrylinla/react-native-sketch-canvas'

  
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'Firebase/Messaging'
  pod 'Firebase/Core'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  

use_native_modules!

  pod 'RNPhotoEditor', :path => '../node_modules/react-native-photo-editor/ios'

use_frameworks!

  pod 'iOSPhotoEditor', :git => 'https://github.com/prscX/photo-editor', :branch => 'master'
  
  post_install do |installer|

    rnfirebase = installer.pods_project.targets.find { |target| target.name == 'RNFirebase' }
    rnfirebase.build_configurations.each do |config|
      config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) ${PODS_ROOT}/Headers/Public/**'
    end

    installer.pods_project.targets.each do |target|
      if target.name.include?('iOSPhotoEditor')
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '5'
        end
      end
    end
  end
  
  target 'ColormycreationsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'Colormycreations-tvOS' do
  # Pods for Colormycreations-tvOS

  target 'Colormycreations-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

//==========POD FILE END=============

NOTE:- But when we create a new project and dont indtall Firebase in it than the code will work fine.

please help me to solve this issue.
My Project was not completed due to this issue.

**Comment by arjundalal** [comment]
Hello Team,
How can i resolve above error.
please help

**Comment by arjundalal** [comment]
Hello Team,
I have Solved the above issue.
Thanks for helping me.

**Comment by mobilestar0223** [comment]
Hello, @arjundalal 
Could you let me know how you make library work for iOS?
Please let me know how you solved #93 and this issue.
Thanks

**Comment by arjundalal** [comment]
Follow same steps as mention in Library Documentation.

**Comment by linhpa** [comment]
> Hello Team,
> I have Solved the above issue.
> Thanks for helping me.

Hi @arjundalal , I'm facing the same issue as yours. How did you solved this issue?

**Comment by Anytram** [comment]
Hi @arjundalal  I have the same issue, did you manage to solve this?
