### ISSUE TITLE
OnDone not saving edited Image

### ISSUE THREAD

**Issue by shahrourit** [prscX/react-native-photo-editor#110]
**Testing on iOS**

Hi

I am retrieving an image from the web, caching it through `RNFetchBlob` and using that path as the image source. Everything up to here works fine. After editing the image, I press the **Arrow (Done)** button, open the image again in the editor from the same location path, and the original shows up. I even checked the folder of the cached images, none of them were edited, they were the originals. 

I am fairly new on React Native, am I missing something?

```
  openImage(url: string) {
    if (this.state.hasPath) {
      this.editImage();
    } else {
      RNFetchBlob.config({
        fileCache: true,
        appendExt: "jpg"
      })
        .fetch("GET", url)
        .then(res => {
          let imgPath = res.path();
          console.log(`Cached in ${imgPath}`); // Caches successfully 
          this.setState({
            hasPath: true,
            path: imgPath
          });
          this.editImage();
        });
    }
  }

  editImage() {
    let imgPath = this.state.path;
    RNPhotoEditor.Edit({
      path: imgPath,
      hiddenControls: ["save", "share"],
      onDone: () => {
        console.log(`Saved in ${imgPath}`);  // Saves in the same cached path successfully
      },
      onCancel: () => {
        console.log("on cancel");
      }
    });
  }

**Comment by shahrourit** [comment]
Never mind, I got it to work.
I had some issues with the state.
Closing issue.

**Comment by aqibnaveed** [comment]
> Never mind, I got it to work.
> I had some issues with the state.
> Closing issue.

What was the issue? & how is it resolved?

**Comment by mohamed-ben-nacef** [comment]
i have the same problem after edit image i only find the old one without change
