### ISSUE TITLE
When we click on Crop  Button the app crash

### ISSUE THREAD

**Issue by arjundalal** [prscX/react-native-photo-editor#118]
Hello Team,
when we click on the crop button the app get crash.
please help me to solve this issue. i have added crop activity in manifest file and i have attach the screen shot of crash log here.
![Screen Shot 2020-02-29 at 10 38 55 AM](https://user-images.githubusercontent.com/54262572/75601339-26e5f400-5ae0-11ea-9262-abf7e9533386.png)

**Comment by prscX** [comment]
@arjundalal: We will be tracking it here [issues/117](https://github.com/prscX/react-native-photo-editor/issues/117).

Thanks
</ Pranav >
