### ISSUE TITLE
Ability to change font size and style

### ISSUE THREAD

**Issue by jdestep93** [prscX/react-native-photo-editor#12]
Would be a really nice feature to be able to change font size and style.  Is there plans to do this in the near future?

BTW really good library so far!

**Comment by prscX** [comment]
Thanks @jdestep93 for sharing items.

At the moment I don't have plans of enabling font size and it's styling. Please feel free to share PR for the same.

Thanks
</ Pranav >

**Comment by prscX** [comment]
@jdestep93: Closing the issue. Since their are no plans as of now to enable the customization features.

Thanks
</ Pranav >
