### ISSUE TITLE
Some of the features are missing on android

### ISSUE THREAD

**Issue by jdestep93** [prscX/react-native-photo-editor#13]
The cropping feature and possibly other features are missing on Android. Please take a look at the following photo. Thank you.

<img width="341" alt="screen shot 2018-10-08 at 8 03 17 am" src="https://user-images.githubusercontent.com/28699033/46607891-a54b8b80-cad0-11e8-814a-20cfa39c2494.png">

**Comment by prscX** [comment]
Thanks @jdestep93 for raising the issue.

It's True. All feature are not supported by the native Android library we have integrated. Basically both iOS and Android libraries are written by same folks. I don't think they have any plans of enabling shared features in near future.

[photo-editor-android](https://github.com/eventtus/photo-editor-android)
[photo-editor](https://github.com/eventtus/photo-editor)

Thanks
</ Pranav >

**Comment by prscX** [comment]
@jdestep93: I believe it is already wired on Android. Are you facing any issues?

Thanks
</ Pranav >

**Comment by jdestep93** [comment]
yeah it doesn't appear that the callbacks are wired up to anything inside the Native module, theyre just passed to the public method `Edit` and thats it

**Comment by prscX** [comment]
Thanks @jdestep93 for the PR and Effort. I am closing this issue since the PR is merged.

Thanks
</ Pranav >
