### ISSUE TITLE
Build failed on android

### ISSUE THREAD

**Issue by harshal2030** [prscX/react-native-photo-editor#133]
```cmd
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:21:7-34
        is also present at [com.github.prscX:photo-editor-android:master-SNAPSHOT] AnroidManifest.xml:12:9-35 value=(true).
        Suggestion: add 'tools:replace="android:allowBackup"' to <application> elemen at AndroidManifest.xml:7:5-117 to override.

```
plz help

**Comment by hamzaouhssain1993** [comment]
az it is written in the log error you just need to go the manifest file and add:

  android:allowBackup="true"

**Comment by leonljy** [comment]
Edit android/app/src/main/AndroidManifest.xml file

There is an option `android:allowBackup` in the <application> tag. Set value to `true`

**Comment by harshal2030** [comment]
Yeah, figured it out. thx

**Comment by GaylordP** [comment]
Hello,

Thanks, I had the problem.
However, what is the impact of this modification and why is it needed for this package ?
Many sites say to handle this variable with care

Thanks you very much in advance

**Comment by kyle-ssg** [comment]
I believe this will persist async storage between uninstalls which is definitely quite undesirable in a lot of cases.

**Comment by kyle-ssg** [comment]
I believe we can also edit our own manifest as follows:

```
<manifest
        xmlns:tools="http://schemas.android.com/tools"
```

```
    <application
            tools:replace="android:allowBackup"
```
