### ISSUE TITLE
RNFetchBlob request error: url === nullnull. Example project.

### ISSUE THREAD

**Issue by Temirtator** [prscX/react-native-photo-editor#140]
I have met this problem when I builded apk. I've noticed 
`let binaryFile = resolveAssetSource(backgroundImage);`
this part of code, generating uri for localhost, even after building apk. How can I fix this problem. So example code, is not working when u build debug apk version. How can I fix this problem?

**Comment by Temirtator** [comment]
I have solved problem. Issues exist because file is not found. 
I've solved the problem by this code:
```
let photoPath = RNFS.DocumentDirectoryPath + name;
    RNFS.readFileRes(name.substring(1, name.length), 'base64').then((file) => {
      RNFS.writeFile(photoPath, file, 'base64')
        .then(() => {
          _onPress();
        })
        .catch((_err) => {
          console.log(_err);
        });
    });
```

**Comment by prscX** [comment]
Thanks @Temirtator for sharing the fix.

You got it right. resolveAssetSource is not supported on production. We need to use RNFS or other FileSystem supported library only.
