### ISSUE TITLE
Edited URI not showing the changes applied instead showing the unedited image

### ISSUE THREAD

**Issue by umair-dpl** [prscX/react-native-photo-editor#145]
onDone: (response) => {
        console.log('response : '+JSON.stringify(response))
       this.editImage(response);
      },

I can fetch the URL but it's not updated even tried saving it in camera roll (explicitly) and then fetching it, still getting the old image @prscX

**Comment by hamzaouhssain1993** [comment]
update the url of the link adding a random variable or a date time, for example:

displayUrl = `${displayUrl}?${new Date().getTime()}`;

**Comment by umair-dpl** [comment]
> update the url of the link adding a random variable or a date time, for example:
> 
> displayUrl = `${displayUrl}?${new Date().getTime()}`;

where the time should be inserted ? for instance I have an image from local storage 
file:///storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20201005-WA0000.jpg"
where I should add the time ? before .jpg and after WhatsApp images ?

**Comment by hamzaouhssain1993** [comment]
just at the end of the path, for exampke your path should be something like

file:///storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20201005-WA0000.jpg?456565636

so in code 
let yourPath = file:///storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20201005-WA0000.jpg
yourPath = ${displayUrl}?${new Date().getTime()}; 

let me know if it does not work, maybe it is related to something else in your case

**Comment by umair-dpl** [comment]
you are a life saver bro it did work :D

**Comment by Bladymendoza97** [comment]
Hello friend, I did what you explained to me in this way, but I still cannot edit the photo.

<img width="599" alt="Captura de Pantalla 2021-07-19 a la(s) 5 42 00 p  m" src="https://user-images.githubusercontent.com/41081923/126240986-2148fcc6-5b7d-416a-b08a-06a8ec3e5c70.png">

**Comment by aharodnikau** [comment]
Why is a edited picture should be saved in random url? Also not working
