### ISSUE TITLE
Cannot compile for Android: package ui.photoeditor does not exist

### ISSUE THREAD

**Issue by SimoneMSR** [prscX/react-native-photo-editor#17]
my **android/app/build.gradle**
```
android{
...
   compileSdkVersion 27
   buildToolsVersion "28.0.2"
...
}
...
dependencies {
...
    compile 'com.android.support:appcompat-v7:27.1.1'
...
}
```
After including the library in my app, and running
`react-native run-android`
I  get .this error
**..android\app\src\main\java\com\rst3\MainApplication.java:6: error: package ui.photoeditor does not exist
import ui.photoeditor.RNPhotoEditorPackage;**
where am I wrong?

**Comment by prscX** [comment]
Thanks @SimoneMSR for raising the issue and fix for the same.

Thanks
</ Pranav >
