### ISSUE TITLE
How to? Building new Featues

### ISSUE THREAD

**Issue by Sebastian-Schuchmann** [prscX/react-native-photo-editor#184]
Hello,

as I understand this Library is a wrapper around two native modules but I am a bit confused as why there is no code for iOS in this repo. Am I missing something? How can I extend the native modules that this Library wrapped?

Cheers, Seppi!

**Comment by prscX** [comment]
@Sebastian-Schuchmann: Library has iOS native module as well, please refer below path

 `https://github.com/prscX/react-native-photo-editor/tree/master/ios`

Thanks,
</ Pranav >
