### ISSUE TITLE
Attempting to access file from path returned from onDone callback does not exist

### ISSUE THREAD

**Issue by jdestep93** [prscX/react-native-photo-editor#19]
There may be an underlying issue with the implementation of saving the file to the specified file path.  May not be working entirely, or there is a race condition where the path is returned before the file is written.

**Comment by guoliang1206** [comment]
so this issue still not be fixed ?

**Comment by hieupaul** [comment]
I'm facing same issue.
I'm using with another lib to choose an photo, then edit it but after that I receive an image before edit.

**Comment by jdestep93** [comment]
Its probably a race condition or permission issue within android. I havent been able to look into the issue lately

**Comment by guoliang1206** [comment]
For iOS, I have check the source code about this lib latest version. It did nothing when after edit photo, It returns nothing to JS. So we can't get the edited photo, I guess the android issue is same. Maybe you could try to fix it. I have create a PR but no one check and merge it.

**Comment by MohdSaleh** [comment]
the photo will be saved in same path with given, I guess its overwriting the same image file.

**Comment by ramondelmondo** [comment]
I'm facing same issue.
I'm using another lib to choose an photo (react-native-image-picker), then edit it but after that I receive an image before edit.

My image uri is like: file:///var/mobile/Containers/Data/Application/58ED7459-1CAC-4B3C-A13A-96DD68CA3462/Documents/images/9F3561AD-A340-442F-8BF9-7141A23170EC.jpg

Please someone can help me?

**Comment by prscX** [comment]
The purpose of library is to edit images which are within app sandbox. Editing external images are not supported.

If we are capturing image using cameraRoll then first we should move that image to app storage then share same path for the edit.

This library overrides same file post editing is done and does not return any path, ideally its the same path.

Thanks
</ Pranav >
