### ISSUE TITLE
Cannot find protocol declaration for 'PhotoEditorDelegate'

### ISSUE THREAD

**Issue by kousiclattala** [prscX/react-native-photo-editor#195]
I'm getting this error when I run my react-native app in ios. I have done the linking as specified in the documentation.
![Screenshot 2021-10-28 at 12 46 41 PM](https://user-images.githubusercontent.com/51958513/139206093-e85e93e3-e158-4ec5-ab7b-ede29f6f26b8.png)
.

**Comment by mudassir912** [comment]
same issue.
any solution??

**Comment by AliRezaBeigy** [comment]
Solution:
Podfile
```
...
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

Add this line ----->   pod 'iOSPhotoEditor', :git => 'https://github.com/prscX/photo-editor', :branch => 'master'

  target 'AppTests' do
    inherit! :complete
    # Pods for testing
  end
....
```

**Comment by prscX** [comment]
@AliRezaBeigy: Thanks for sharing the fix.

@mudassir912: You could also refer the installation steps defined [here](https://github.com/prscX/react-native-photo-editor#-getting-started).

Thanks, </ Pranav >
