### ISSUE TITLE
Path param error

### ISSUE THREAD

**Issue by srameshr** [prscX/react-native-photo-editor#2]
The ```path``` key value is ```file:///Users/username/Library/Developer/CoreSimulator/Devices/42134366-48F1-46B6-951B-A525B89B82C0/data/Containers/Data/Application/606F6963-86A0-4E16-8124-8F5F3C5E5EB7/Documents/8D11DDDE-D992-489F-B7EA-627A86AF8B3F.jpg```

```
2018-09-13 15:28:38.180634+0530 Frills[70239:1900744] [framework] CUICatalog: Invalid asset name supplied: '(null)'
2018-09-13 15:28:38.180824+0530 Frills[70239:1900744] [framework] CUICatalog: Invalid asset name supplied: '(null)'
2018-09-13 15:28:38.181080+0530 Frills[70239:1900744] [framework] CUICatalog: Invalid asset name supplied: '(null)'
2018-09-13 15:28:38.181295+0530 Frills[70239:1900744] [framework] CUICatalog: Invalid asset name supplied: '(null)'
Fatal error: Unexpectedly found nil while unwrapping an Optional value
2018-09-13 15:28:38.569267+0530 Frills[70239:1900744] Fatal error: Unexpectedly found nil while unwrapping an Optional value
```

**Comment by prscX** [comment]
Hi @srameshr: I have tried the same using image name as `8D11DDDE-D992-489F-B7EA-627A86AF8B3F.jpg` and it is working as expected.

Thanks
</ Pranav >

**Comment by prscX** [comment]
@srameshr: Please find below snippet for providing the path:

`RNFS.DocumentDirectoryPath + "/8D11DDDE-D992-489F-B7EA-627A86AF8B3F.jpg";` 

Thanks
</ Pranav >

**Comment by srameshr** [comment]
So, should I install react native file system package?

**Comment by prscX** [comment]
@srameshr: Can you share how you are fetching the stored file path currently?

Thanks
</ Pranav >

**Comment by srameshr** [comment]
From react-native-camera.
```
this.camera.takePictureAsync().done((data) => {
  RNPhotoEditor.Edit({
    path: data.uri,
  });
});
```

**Comment by srameshr** [comment]
@prscX Anything on this?

**Comment by prscX** [comment]
@srameshr: I believe `takePictureAsync` API will capture image and save within its own application. We need to `move/copy` the same within our app and then using `RNFS` you can obtain the path.

Please feel free to share your thoughts on the same.

Thanks
</ Pranav >

**Comment by srameshr** [comment]
Isn't that path available to every module within the sandbox? I see other apps such as RN Adobe editor can access the image. The same thing happens when selecting images from photos or gallery.

**Comment by srameshr** [comment]
@prscX Could you show an example of how you are supplying the image path to the editor? Try to take picture from RN camera or RN photos

**Comment by prscX** [comment]
Hi @srameshr: I have not tried it by using RNCamera || RNPhotos.  

In library example, I have used RNFS to write the image in local file system and provided the same path to the library.

Coming weekend, I will try the same using RNCamera || RNPhotos. Will share my results.

Thanks
</ Pranav >

**Comment by nbadag** [comment]
Hi @prscX & @srameshr — I ran into this same issue with `RNCamera` alongside [`react-native-image-crop-picker`](https://github.com/ivpusic/react-native-image-crop-picker). The difference between the two is that the picker (which worked fine with the editor) returns just a path without protocol, e.g. `/Users/username/Library...`, while the camera component returns a path with `file:///` at the front of it.

If I had to guess, I'd say the editor is internally adding the protocol, such that what it's trying to load is actually `file:///file:///Users/username/Library...`. Just stripping out the protocol at the beginning of the uri returned from `RNCamera` with a string `.replace()` solved the issue for me.

**Comment by srameshr** [comment]
Great catch, let me just verify it again

**Comment by leksyib** [comment]
@srameshr Hi! have you found a fix?

**Comment by srameshr** [comment]
@leksyib @nbadag I did try it but it does not work.  It does not throw an error nor open the editor

**Comment by leksyib** [comment]
Wow, I'll try saving the photo from the camera first then picking the saved
path from the editor.

On Sep 25, 2018 8:42 AM, "Siddharth Ramesh" <notifications@github.com>
wrote:

@leksyib <https://github.com/leksyib> @nbadag <https://github.com/nbadag> I
did try it but it does not work. It does not throw an error nor open the
editor

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/prscX/react-native-photo-editor/issues/2#issuecomment-424239964>,
or mute the thread

**Comment by leksyib** [comment]
@srameshr  this works.. Issue can be closed
<img width="494" alt="screen shot 2018-09-26 at 2 36 12 pm" src="https://user-images.githubusercontent.com/26174035/46083561-9c39f080-c199-11e8-826a-5c1ef670fde2.png">

**Comment by srameshr** [comment]
Just tried the same thing. It does not work nor does it throw an error. The screen just flashes once. That is about it. I do not see any logs on xcode.

**Comment by prscX** [comment]
Hi @srameshr: @tonimoeckel has raised a PR w.r.t `iOS: Read image as data from path`. Hope that might have solved the issue.

Can you please install latest version and verify the same. Please let us know incase you face any issues.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @srameshr: I hope the issues was resolved in latest version. For now I am closing the issues. Please let me know in case you still face the same issue.

Thanks
</ Pranav >

**Comment by srameshr** [comment]
Sure, I will.

**Comment by bharatidudhjiya** [comment]
I have same issue with **ImagePickerIOS**
There is any one to solved this issue.

Thanks!

**Comment by Anytram** [comment]
Hi, I have the same issue, did you solve it?
