### ISSUE TITLE
Crop option is not working (Android only)

### ISSUE THREAD

**Issue by mnjsnj** [prscX/react-native-photo-editor#204]
First of all thank you for adding the crop option into android too  and cropping  in iOS working fine but in android crop option is not working properly

**Comment by prscX** [comment]
@mnjsnj: Thanks for raising the issue.

I have just tried the same thing, but I am not able to  reproduce the same. Could you please share recording of the same.

Thanks,
Pranav

**Comment by memanoj** [comment]
Hi i fix the this issue please check #190 may hope it will help you so i am closing the issue now so i requested to [prscX](https://github.com/prscX) to check this and update it the git repo it will help to other developer also in Android who are stuck in this issue.
