### ISSUE TITLE
Unable to run iOS version

### ISSUE THREAD

**Issue by Abdulhaque4241** [prscX/react-native-photo-editor#235]
I'm encountering issues running the package on iOS after installing the package.

Here i'm attaching the **Podfile**:

```
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

pod 'GoogleUtilities', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true
pod 'FirebaseCoreExtension', :modular_headers => true
pod 'FirebaseInstallations', :modular_headers => true
pod 'GoogleDataTransport', :modular_headers => true
pod 'nanopb', :modular_headers => true
$RNFirebaseAsStaticFramework = true

use_frameworks! :linkage => :static

flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

$static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
  'CocoaAsyncSocket', 'ComponentKit', 'Flipper-DoubleConversion',
  'Flipper-Glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
  'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native']

pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  installer.pod_targets.each do |pod|
    if $static_framework.include?(pod.name)
      def pod.build_type;
        Pod::BuildType.static_library
      end
    end
  end
end

target 'Inspection' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :flipper_configuration => FlipperConfiguration.disabled,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  pod 'RNPhotoEditor', :path => '../node_modules/react-native-photo-editor/ios'
  pod 'iOSPhotoEditor', :git => 'https://github.com/prscX/photo-editor', :branch => 'master'

  target 'InspectionTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
installer.pods_project.targets.each do |target|
      if target.name.include?('iOSPhotoEditor')
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '5'
        end
      end
    end
  end
end
```

**Comment by srinu6** [comment]
I am also facing the same issue, I was able to fix the build but the app is crashing while calling edit.

**Comment by Abdulhaque4241** [comment]
@srinu6, I was able to run it now. However, after selecting the image, the editor is not visible (and there are no error messages displayed). Previously, I also encountered crashes when calling the edit function, but that issue seems to be resolved now. It appears to be related to the path.

**Comment by srinu6** [comment]
Would you mind sharing how you fixed the path issue? In my case while calling the edit function, seeing a crash due to an error in main.h file. it was saying some error related to PhotoEditorViewController. Is it the same with you? @Abdulhaque4241

**Comment by Abdulhaque4241** [comment]
@srinu6 in which platform you're facing the path issue ?
for me in android i split like this and works fine:
const filePath = images[0].filePath.replace('file://', '');

then used as 
ImageEditor.Edit({
path: filePath
...
})

In iOS, the editor does not open at all, but there is no crash. I'm checking that. I think it should be related to path only.
Also, in between i'm able to open the editor. for iOS filePath split is not needed.

**Comment by srinu6** [comment]
In Android, it worked for me as well @Abdulhaque4241, but in iOS I am seeing this issue, let me know if you are able to fix this bro! it would be helpful. If I can fix then I will be sharing how to fix this. 
Let's connect over [LinkedIn](https://www.linkedin.com/in/srinuvasarao-maripi/)

**Comment by Abdulhaque4241** [comment]
Sure @srinu6 :)
