### ISSUE TITLE
iOS Stickers

### ISSUE THREAD

**Issue by maint14** [prscX/react-native-photo-editor#26]
Hi,
I noticed that on ios when I try to add a sticker to the image, it shows me two pages, the first one empty. Is it possible to add stickers on that page? If so how?

**Comment by d2luu** [comment]
You can place sticker images to Resources folder under your project in Xcode.
![screen shot 2018-11-26 at 4 39 05 pm](https://user-images.githubusercontent.com/14581772/48999433-04a54e00-f19a-11e8-87f5-865d2524eee1.png)

**Comment by maint14** [comment]
My mistake, the array stickers for the edit method were missing

**Comment by vinayak-nangnurkar** [comment]
@maint14  have you resolved it ? can you please help me . i am facing same problem in android
