### ISSUE TITLE
Image does not open on android

### ISSUE THREAD

**Issue by silvaSenna** [prscX/react-native-photo-editor#27]
Copy your sample to test your application, test it on my phone
the same did not open the image to edit, could you help me?

import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  TouchableOpacity,PermissionsAndroid
} from 'react-native';
import resolveAssetSource from "react-native/Libraries/Image/resolveAssetSource";

import { RNPhotoEditor } from 'react-native-photo-editor';

import RNFS from 'react-native-fs';
import RNFetchBlob from 'rn-fetch-blob';

import photo from './photo.jpg';

export default class App extends Component<Props> {
  constructor(props) {
    super(props)

    this.state = {
      visible: false
    }
  }

  _onPress() {
    let filter;
    if (Platform.OS === 'ios') {
      filter = [];
    } else if (Platform.OS === 'android') {
      filter = ".*\\.*";
    }

    RNPhotoEditor.Edit({
      path: RNFS.DocumentDirectoryPath + "/photo.jpg",
      stickers: [
        "sticker0",
        "sticker1",
        "sticker2",
        "sticker3",
        "sticker4",
        "sticker5",
        "sticker6",
        "sticker7",
        "sticker8",
        "sticker9",
        "sticker10"
      ],
      hiddenControls: [],
      colors: undefined,
      onDone: () => {
        console.log('on done')
      },
      onCancel: () => {
        console.log('on cancel')
      }
    });
  }

  componentDidMount() {

     const granted= PermissionsAndroid.request(
       PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE,{
         'title':'Exitus permissão',
         'message':'Precisa de permissão para abrir imagens'

       });

    let photoPath = RNFS.DocumentDirectoryPath + "/photo.jpg";
    let binaryFile = resolveAssetSource(photo)

    RNFetchBlob.config({ fileCache: true })
      .fetch("GET", binaryFile.uri)
      .then(resp => {
        RNFS.moveFile(resp.path(), photoPath)
          .then(success => {
            console.log("FILE WRITTEN!");
          })
          .catch(err => {
            console.log(err.message);
          });
      })
      .catch(err => {
        console.log(err.message);
      });
  }

  render() {
    return <View style={styles.container}>
      <TouchableOpacity onPress={() => {
        this._onPress()

        // this.setState({ visible: true });
      }}>
        <Text>Click</Text>
      </TouchableOpacity>
    </View>;
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  }
});
![screenshot_20181125-184747](https://user-images.githubusercontent.com/5387004/48985380-91420480-f0e5-11e8-86f2-ef0fffeac7c5.png)

**Comment by FrickenHamster** [comment]
I had this problem and managed to find a fix.
My image picker and camera returned an image path that started with 
`file///`

I just stripped the prefix and it worked.

**Comment by ZeitounCorp** [comment]
Hey There I am not sure on how to strip the prefix could you tell me more on this please  @FrickenHamster 

> I had this problem and managed to find a fix.
> My image picker and camera returned an image path that started with
> `file///`
> 
> I just stripped the prefix and it worked.

**Comment by FrickenHamster** [comment]
For me, the path being passed in started with 
`file///` on android. I took that part out of the path string and it worked for me.

**Comment by yasirdev** [comment]
I'm unable to generate release build for android, error occurred for duplicate resources.

Can anyone please help!

**Comment by HectorQuinonesBarrios** [comment]
Im using expo camera and passing the resulting uri, but i can't get it to work, no matter how i strip the `file///`

**Comment by prscX** [comment]
Hi @HectorQuinonesBarrios: Try by moving captured image to App sandbox and then pass file path to the same. You can use RNFS to achieve the same.

Thanks
</ Pranav >

**Comment by AKcrisAshish** [comment]
try this:
image.path.replace('file://','')

I am sure that It will help you .

**Comment by vedbhawsar** [comment]
I am facing this same issue. My image picker gives me a path something like this: 
`    content://com.android.providers.media.documents/document/image%3A69315`
I am calling the edit function like this:

``` 
RNPhotoEditor.Edit({
      path: decodeURIComponent(content://com.android.providers.media.documents/document/image%3A69315)
});
```

can someone suggest a solution?

**Comment by AmmarAshfaq** [comment]
> @prscX
> I am facing this same issue. My image picker gives me a path something like this:
> ` content://com.android.providers.media.documents/document/image%3A69315`
> I am calling the edit function like this:
> 
> ```
> RNPhotoEditor.Edit({
>       path: decodeURIComponent(content://com.android.providers.media.documents/document/image%3A69315)
> });
> ```
> 
> can someone suggest a solution?

same issue

**Comment by prscX** [comment]
The purpose of library is to edit images which are within app sandbox. Ideally post capturing any image we need to move it to app storage and then share that path for the editing with this library.

Thanks
</ Pranav >

**Comment by VivekkChudasama** [comment]
@prscX Hi,

Image Editor functionality completed after Updated image not showing.

I'm using the latest plugin. `("react-native-photo-editor": "^1.0.8")`

**Comment by LcBaixiao** [comment]
> For me, the path being passed in started with `file///` on android. I took that part out of the path string and it worked for me.

Nice，bro
