### ISSUE TITLE
Idea - possibility to apply filters programatically 

### ISSUE THREAD

**Issue by ddereszewski** [prscX/react-native-photo-editor#3]
use case: 
1. User use the solution to put the sticker on the picture. 
2. The applied filters can be  saved 
3. The filters can be used in the code to be applied on the other images without user interaction, and saved. 

Let me know if that makes sense. Happy to contribute

**Comment by prscX** [comment]
Thanks @ddereszewski for sharing your thoughts.

I believe below shared ideas are already in place:
* User use the solution to put the sticker on the picture.
* The applied filters can be saved

May be I have misunderstood. 

You are always welcome and appreciated for any type of contribution.

Thanks
</ Pranav >
