### ISSUE TITLE
can't open the editor after click text

### ISSUE THREAD

**Issue by nikamamruta** [prscX/react-native-photo-editor#30]
app carshes after click text click..without any error

**Comment by dqhung311** [comment]
Please ensure your image is exist

**Comment by prscX** [comment]
@dqhung311: Thanks for your response.

@nikamamruta: Please verify the image exist in app sandbox, sometime it has issues in writing the image but usually it should work. I would recommend to try this with latest release.

Let me know incase you still face same issue.

Thanks
</ Pranav >
