### ISSUE TITLE
Crop missing on Android

### ISSUE THREAD

**Issue by SimonDrew2018** [prscX/react-native-photo-editor#32]
Not sure if this is the same as one of the closed issues so apologies if it is. There is no option for cropping on Android. I've tested on 3 different Android devices & the simulator but all are the same.

RNPhotoEditor.Edit({
  path: response.path,
  hiddenControls: ['save'],
  onCancel: () => { Actions.pop() },
  onDone: () => { Actions.refresh({ key: Math.random() }) }
});

I've read through the documentation but looks as though this should be shown as default since its not in my 'hiddenControls' array. You can see in the first image there is no crop option but in the second image taken from the documentation you can see it is there.

[https://i.stack.imgur.com/KR34t.png](url)
[https://i.stack.imgur.com/RfKj1.png](url)

**Comment by prscX** [comment]
Thanks @SimonDrew2018 for raising the issue.

Crop functionality is only supposed for iOS on Android it is not supported.

Thanks
</ Pranav >

**Comment by DavitVosk** [comment]
@prscX can you please advice whether you plan integration image cropping into Android as well?

@SimonDrew2018 how did you solve the problem with image cropping?

**Comment by prscX** [comment]
Hi @DavitVosk: This library has a native dependency on [photo-editor-android](https://github.com/eventtus/photo-editor-android) which does not support the crop functionality on Android. Looking at the repo, I think the work is stalled.

Considering effort, challenges and bandwidth, at moment, I don't think I have space of enabling this feature, however please feel free to share PR in case you enable the same.

Thanks
</ Pranav >

**Comment by SimonDrew2018** [comment]
Thanks @prscX works perfectly on iOS, appreciate it!

@DavitVosk for iOS I use react-native-photo-editor as everything works. For Android I use react-native-image-crop-picker, crop the image and then pass through the cropped image to react-native-photo-editor to edit the image. It actually works pretty well!

**Comment by DavitVosk** [comment]
Hi @SimonDrew2018, unfortunately it will not work for me. I need custom aspect ratio here
