### ISSUE TITLE
Prevent file saving to cameraRoll

### ISSUE THREAD

**Issue by jothikannan** [prscX/react-native-photo-editor#33]
Is there any way to save the Edited image to a particular folder/App, currently it saving on both given file path and also saving on cameraRoll too. So images are available in both the places. 

Just think that I am developing an App that has camera and gallery feature to capture and save photos inside the app only, and additionally, I want to add this Editing feature too. In this case, Edited images will be saved in both places. Which is functionally wrong.

**Comment by cristianoccazinsp** [comment]
Figured it out? Have the same requirement.

**Comment by prscX** [comment]
Thanks @jothikannan for raising the query.

This library supports editing images which are within app sandbox, however editing directly from cameraRoll functionality was enabled in one of the raised PR.

I would recommend to move image first from cameraRoll to app sandbox and then provide its path to this library, doing this it will not override the cameraRoll image.

Thanks
</ Pranav >
