### ISSUE TITLE
Crop Option

### ISSUE THREAD

**Issue by dinesh-rudra** [prscX/react-native-photo-editor#35]

**Comment by dinesh-rudra** [comment]
There is no crop option available. 
Rest is good.

**Comment by ahadali** [comment]
> There is no crop option available.
> Rest is good.

Yes I also found the same issue, all the options were appearing except the crop one. @prscX  do we have to install separate library for crop?

**Comment by prscX** [comment]
Hi @ahadali: As part of Android native library integration, it does not have support for Crop functionality. It is supported only on iOS. I believe, someone from community have integrated a separate Crop library to achieve the same.

-> Once the picture is edited through the library you can use third part crop library to achieve the same.

Thanks
</ Pranav >

**Comment by ahadali** [comment]
Thanks @prscX  for your response.

**Comment by DavitVosk** [comment]
@ahadali what cropping package do you use for Android please?

**Comment by ahadali** [comment]
> @ahadali what cropping package do you use for Android please?
Hi @DavitVosk you can use React Native Image Crop Picker. Here is the link for that https://www.npmjs.com/package/react-native-image-crop-picker/v/0.4.2

**Comment by RZulfikri** [comment]
@dinesh-rudra @ahadali @DavitVosk can you test my PR?

**Comment by prscX** [comment]
Thanks @RZulfikri for the Effort and PR.

Latest version `V1.*` contains crop feature on Android as well. Could you please install latest version and verify the same. Let me know incase it does not work.

Thanks
</ Pranav >
