### ISSUE TITLE
Adding text deletes the previous drawing

### ISSUE THREAD

**Issue by j0araya** [prscX/react-native-photo-editor#38]
Hello, thanks for this repo.

I have this problem: after draw in the photo, then when I add text the previous drawing is deletes.

Tested on two different android devices with same results.

"react-native": "0.55.4"
"react-native-photo-editor": "0.0.7"

![20190102_175126](https://user-images.githubusercontent.com/11578634/50612590-373d1780-0eb9-11e9-96a2-f37cf6088294.gif)

**Comment by aurimas535** [comment]
This is potentially fix https://github.com/aurimas535/react-native-photo-editor/commit/390c02fbf1e107b19f1da863d68e1c7f351dbf29

**Comment by prscX** [comment]
@aurimas535: I have pulled the suggested changes and pushed the release.

@j0araya: Thanks for reporting the issue. Please find fix in the latest release [V1.0.2]. Let me know incase it does not work.

Thanks
</ Pranav >
