### ISSUE TITLE
NativeModules returns empty object in iOS

### ISSUE THREAD

**Issue by Tenkensui** [prscX/react-native-photo-editor#41]
Hello!

I have made an implementation following the available example and it works perfectly in Android but in iOS the `const { RNPhotoEditor } = NativeModules;` from RNPhotoEditor.js always evaluates to null because NativeModules is an empty object.

I have taken a look to the swift code on the RNPhotoEditor.m and the modules seems to be exported correctly so I really have no clue of what could be missing here.

**Comment by Tenkensui** [comment]
Hey, have you figured out anything about this?

**Comment by prscX** [comment]
Thanks @Tenkensui for raising the issue.

This happens when installation steps might got missed. Could you check README and try the same, please.

Thanks
</ Pranav >

**Comment by prscX** [comment]
@Tenkensui: Could you please install latest version of library and verify [V.1*]. Please follow installation steps defined in README.

Let me know incase you still face similar issue.

Thanks
</ Pranav >
