### ISSUE TITLE
Canvas.CLIP_SAVE_FLAG Error

### ISSUE THREAD

**Issue by ranchhodrathod89** [prscX/react-native-photo-editor#44]
Canvas.CLIP_SAVE_FLAG Error in react native version 0.58.6 with compileSdkVersion 28 and buildToolsVersion '28.0.2'
![screen shot 2019-03-03 at 9 18 35 pm](https://user-images.githubusercontent.com/8505328/53697696-00707880-3dfa-11e9-8d3a-207ef9bdc04d.png)

**Comment by naoey** [comment]
I'm not too familiar with Android's Canvas and what the save flags imply, but after the deprecation of these flags in platform 28 replacing `canvas.save(Canvas.CLIP_SAVE_FLAG)` with `canvas.save()` seems to work fine as far as the photo editor's functionality is concerned. I am currently using a local version of this package with this change.

Any ETA on when this issue will be resolved in this package so that I can switch back to it?

**Comment by vishnudbimcs** [comment]
thanks @naoey  this solved my issue

**Comment by prscX** [comment]
Thanks @ranchhodrathod89 for raising the issue.

This is fixed in the latest release `V1.*`. Please install latest version, let me know incase you still face the same issue.

Thanks
</ Pranav >

**Comment by AhmedZaki5** [comment]
protected boolean drawChild(Canvas canvas, View child, long drawingTime) {
    boolean result;
    final int save = canvas.save(Canvas.CLIP_SAVE_FLAG);

    if (mSlideableView != child) { // if main view
        // Clip against the slider; no sense drawing what will immediately
        // be covered,
        // Unless the panel is set to overlay content
        canvas.getClipBounds(mTmpRect);
        if (!mOverlayContent) {
            if (mIsSlidingUp) {
                mTmpRect.bottom = Math.min(mTmpRect.bottom, mSlideableView.getTop());
            } else {
                mTmpRect.top = Math.max(mTmpRect.top, mSlideableView.getBottom());
            }
        }
        if (mClipPanel) {
            canvas.clipRect(mTmpRect);
        }

        result = super.drawChild(canvas, child, drawingTime);

        if (mCoveredFadeColor != 0 && mSlideOffset > 0) {
            final int baseAlpha = (mCoveredFadeColor & 0xff000000) >>> 24;
            final int imag = (int) (baseAlpha * mSlideOffset);
            final int color = imag << 24 | (mCoveredFadeColor & 0xffffff);
            mCoveredFadePaint.setColor(color);
            canvas.drawRect(mTmpRect, mCoveredFadePaint);
        }
    } else {
        result = super.drawChild(canvas, child, drawingTime);
    }

    canvas.restoreToCount(save);

    return result;
}
الخطأ في السطر المحدد. final int save = canvas.save (Canvas.CLIP_SAVE_FLAG)؛

كيفية إصلاح الخطأ؟ API28 إزالة هذه الوظيفة. أحتاج مساعدتك في إصلاحه. أن في التحويل البرمجي لن يسبب خطأ. شكر

**Comment by AhmedZaki5** [comment]
@Override
  protected boolean drawChild(Canvas canvas, View child, long drawingTime) {
    final LayoutParams lp = (LayoutParams) child.getLayoutParams();
    boolean result;
    final int save = canvas.save(Canvas.** @CLIP_SAVE_FLAG**);

    boolean drawScrim = false;

    if (mCanSlide && !lp.slideable && mSlideableView != null) {
      // Clip against the slider; no sense drawing what will immediately be covered,
      // Unless the panel is set to overlay content
      if (!mOverlayContent) {
        canvas.getClipBounds(mTmpRect);
        if (mIsSlidingUp) {
          mTmpRect.bottom = Math.min(mTmpRect.bottom, mSlideableView.getTop());
        } else {
          mTmpRect.top = Math.max(mTmpRect.top, mSlideableView.getBottom());
        }
        canvas.clipRect(mTmpRect);
      }
      if (mSlideOffset < 1) {
        drawScrim = true;
      }
    }

    result = super.drawChild(canvas, child, drawingTime);
    canvas.restoreToCount(save);

    if (drawScrim) {
      final int baseAlpha = (mCoveredFadeColor & 0xff000000) >>> 24;
      final int imag = (int) (baseAlpha * (1 - mSlideOffset));
      final int color = imag << 24 | (mCoveredFadeColor & 0xffffff);
      mCoveredFadePaint.setColor(color);
      canvas.drawRect(mTmpRect, mCoveredFadePaint);
    }

    return result;
  }

**Comment by AhmedZaki5** [comment]
protected boolean drawChild(Canvas canvas, View child, long drawingTime) {
    boolean result;
    final int save = canvas.save(Canvas.CLIP_SAVE_FLAG);

    if (mSlideableView != child) { // if main view
        // Clip against the slider; no sense drawing what will immediately
        // be covered,
        // Unless the panel is set to overlay content
        canvas.getClipBounds(mTmpRect);
        if (!mOverlayContent) {
            if (mIsSlidingUp) {
                mTmpRect.bottom = Math.min(mTmpRect.bottom, mSlideableView.getTop());
            } else {
                mTmpRect.top = Math.max(mTmpRect.top, mSlideableView.getBottom());
            }
        }
        if (mClipPanel) {
            canvas.clipRect(mTmpRect);
        }

        result = super.drawChild(canvas, child, drawingTime);

        if (mCoveredFadeColor != 0 && mSlideOffset > 0) {
            final int baseAlpha = (mCoveredFadeColor & 0xff000000) >>> 24;
            final int imag = (int) (baseAlpha * mSlideOffset);
            final int color = imag << 24 | (mCoveredFadeColor & 0xffffff);
            mCoveredFadePaint.setColor(color);
            canvas.drawRect(mTmpRect, mCoveredFadePaint);
        }
    } else {
        result = super.drawChild(canvas, child, drawingTime);
    }

    canvas.restoreToCount(save);

    return result;
}
The error is in the given line. final int save = canvas.save(Canvas.CLIP_SAVE_FLAG);

how to fix the error? API28 removed this function. I need your help fix it. That at compilation would not cause an error. thank
