### ISSUE TITLE
iOS: save image when permission denied

### ISSUE THREAD

**Issue by d2luu** [prscX/react-native-photo-editor#45]
@prscX 
I deny `save to library` permission on iOS when press save button but it still alerts `Image Saved`.
I fixed it in `PhotoEditor+Controle.swift` file under Pods/iOSPhotoEditor folder for myself.
How can I make a PR with change to swift file in iOS? Because all file in **ios/Pods/*** was ignored in .gitignore so I can't.

**Comment by prscX** [comment]
Thanks @d2luu for raising issue and solution.

Please feel free to share PR on the below project, once merged will be reflect on next installation.

https://github.com/prscX/photo-editor

Thanks
</ Pranav>
