### ISSUE TITLE
Install from CocoaPods

### ISSUE THREAD

**Issue by naoey** [prscX/react-native-photo-editor#47]
I recently migrated my project away from using libraries (including React) linked to my Xcode project, instead including everything through the CocoaPods workspace. Since then I have been unable to use this library on iOS because the current setup only seems to link to the Xcode project. Due to this the React header files don't get resolved when building with this library since they are in the Pod workspace.

I tried adding the podspec to this library in my Podfile as `pod 'RNPhotoEditor', :path => '../node_modules/react-native-photo-editor/ios'` but it doesn't seem to copy over all the necessary files since they are not included in the workspace:
<img width="204" alt="image" src="https://user-images.githubusercontent.com/3889501/54660912-3f8f1100-4afe-11e9-9c2f-ca18e2da9469.png">

Is it possible to update the Podfile and install steps to add the whole library as well as the iOSPhotoEditor framework through CocoaPods entirely? I believe the extra step of running `pod install` inside node_modules could also be eliminated that way. The [`react-native-image-crop-picker`](https://github.com/ivpusic/react-native-image-crop-picker) library might serve as a good example since they also have several Pod dependencies and recommend installing the library through CocoaPods.

**Comment by prscX** [comment]
Thanks @naoey for raising the issue.

It is fixed in the latest released version. Could you install and verify the same, please follow installation steps defined on `README`. Let me know incase you still face the same issue.

Thanks
</ Pranav >
