### ISSUE TITLE
Modified Picture on onDone

### ISSUE THREAD

**Issue by saxs4x** [prscX/react-native-photo-editor#48]
Is it possibile to have the modified image returned as an argument of the onDone callback? It's vital to me.

**Comment by cdan1995** [comment]
+1
I need feature. Please

**Comment by RZulfikri** [comment]
@cdan1995 @saxs4x try and test my fork.

**Comment by prscX** [comment]
Thanks for raising the issue.

`Edit`API modify the shared URI image and saves the changes at the same location.  If you are capturing the image, it is recommended first you move file to app sandbox then provide its storage path to edit the same.

Thanks
</ Pranav >
