### ISSUE TITLE
null is not an object(evaluating RNPhotoEditor.Edit)

### ISSUE THREAD

**Issue by AKcrisAshish** [prscX/react-native-photo-editor#49]
This is my code :

import React, { Component } from 'react';
import { Text, Image, Platform,TouchableOpacity } from 'react-native';
import { RNPhotoEditor } from 'react-native-photo-editor';
import RNFS from 'react-native-fs';
import Cam from 'react-native-vector-icons/FontAwesome';
import Photu from 'react-native-vector-icons/FontAwesome';
import Collage from 'react-native-vector-icons/FontAwesome';
import { ParentHomeContainer, FirstChild, SecondChild, SecondChild1, SecondChild11, SecondChild12, SecondChild13 } from '../../styles/HomeStyles';
import resolveAssetSource from 'react-native/Libraries/Image/resolveAssetSource';
import photo from '../../assets/back.jpg';
import RNFetchBlob from 'rn-fetch-blob'

class HomeScreen extends Component {
    constructor(props) {
        super(props)
    
        this.state = {
          visible: false
        }
      }
      _onPress() {
        let filter;
        if (Platform.OS === 'ios') {
          filter = [];
        } else if (Platform.OS === 'android') {
          filter = ".*\\.*";
        }
    
        RNPhotoEditor.Edit({
          path: RNFS.DocumentDirectoryPath + "/photo.jpg",
          stickers: [
            "sticker0",
            "sticker1",
            "sticker2",
            "sticker3",
            "sticker4",
            "sticker5",
            "sticker6",
            "sticker7",
            "sticker8",
            "sticker9",
            "sticker10"
          ],
          hiddenControls: [],
          colors: undefined,
          onDone: () => {
            console.log('on done')
          },
          onCancel: () => {
            console.log('on cancel')
          }
        });
      }
    
      componentDidMount() {
        let photoPath = RNFS.DocumentDirectoryPath + "/back.jpg";
        let binaryFile = resolveAssetSource(photo)
    
        RNFetchBlob.config({ fileCache: true })
          .fetch("GET", binaryFile.uri)
          .then(resp => {
            RNFS.moveFile(resp.path(), photoPath)
              .then(success => {
                console.log("FILE WRITTEN!");
              })
              .catch(err => {
                console.log(err.message);
              });
          })
          .catch(err => {
            console.log(err.message);
          });
      }
    render() {
        return (
            <ParentHomeContainer source={require('/Volumes/DATA /React Native/ImgEditor/src/assets/back.jpg')}>

                <FirstChild>
                    <Image style={{ height: 50, marginBottom: 7, width: 50, borderRadius: 25, backfaceVisibility: 'hidden' }}
                        source={require('/Volumes/DATA /React Native/ImgEditor/src/img/HomeBackground/p-letter-wings-logo-design-with-black-bird-fly-vector-20684683.jpg')}
                    />
                    <Text style={{ color: 'white', fontWeight: '200', fontSize: 40 }}>icsLab</Text>
                </FirstChild>

                <SecondChild>
                    <SecondChild11>
                        <TouchableOpacity onPress={() => { this._onPress() }}
                            style={{ alignItems: 'center' }}>
                            <Cam name='camera-retro'
                                color='white'
                                backgroundColor='transparent'
                                size={35} />
                            <Text style={{ color: 'white', marginTop: 5, fontWeight: '400' }}>Camera</Text>
                        </TouchableOpacity>
                    </SecondChild11>
                    <SecondChild12>
                        <TouchableOpacity style={{ alignItems: 'center' }}>
                            <Photu name='picture-o'
                                color='white'
                                backgroundColor='transparent'
                                size={35} />
                            <Text style={{ color: 'white', marginTop: 5, fontWeight: '400' }}>Photos</Text>
                        </TouchableOpacity>
                    </SecondChild12>
                    <SecondChild13>
                        <TouchableOpacity style={{ alignItems: 'center' }}>
                            <Collage name='th'
                                color='white'
                                backgroundColor='transparent'
                                size={35} />
                            <Text style={{ color: 'white', marginTop: 5, fontWeight: '400' }}>Collage</Text>
                        </TouchableOpacity>
                    </SecondChild13>
                </SecondChild>

            </ParentHomeContainer>
        )
    }
}
export default HomeScreen;

**Comment by PrakharTU** [comment]
change ` path: RNFS.DocumentDirectoryPath + "/photo.jpg",` to ` path: RNFS.DocumentDirectoryPath + "/back.jpg",` in `RNPhotoEditor.Edit()`

**Comment by AKcrisAshish** [comment]
I have done it . but getting a new error 
"null is not an object(evaluating 'RNFetchBlob.DocumentDir')

**Comment by PrakharTU** [comment]
Did you use
`react-native link`

**Comment by AKcrisAshish** [comment]
yes I am  done with every installations and linkings

**Comment by AKcrisAshish** [comment]
![Screen Shot 2019-03-29 at 8 32 04 PM](https://user-images.githubusercontent.com/48308108/55241828-f78c8e80-5261-11e9-8b2d-68fb73f31575.png)

**Comment by antoniomdk** [comment]
I have the same problem, Did you fix it?

**Comment by AhmedAliIbrahim** [comment]
anyone find a solution for this issue ?

**Comment by bamaarintoko** [comment]
anyone fixed this?

**Comment by hoonblizz** [comment]
I endedup here. Any solution yet?

**Comment by saxs4x** [comment]
This doesn't work in android too. Any solution? someone managed to make it work?

**Comment by prscX** [comment]
Thanks for raising issue.

Could you please try using latest version and migrate your app to RN61. Please follow installation steps defined in `README`. Let me know incase it does not work.

Thanks
</ Pranav >

**Comment by anudr01d** [comment]
For anybody getting this issue - The fix for me was to add the following line within podfile 

`pod 'RNPhotoEditor', :path => '../node_modules/react-native-photo-editor/ios'`

**Comment by dotku** [comment]
> For anybody getting this issue - The fix for me was to add the following line within podfile
> 
> `pod 'RNPhotoEditor', :path => '../node_modules/react-native-photo-editor/ios'`

Did this, but I still got error:

>  ERROR  TypeError: null is not an object (evaluating 'RNPhotoEditor.Edit')

<img width="387" alt="image" src="https://user-images.githubusercontent.com/1519232/183511954-9fdfaa6d-a915-47bc-a02a-11e21f0065d8.png">

**Comment by HummaSaeed** [comment]
How this issue will be fixed on android?

**Comment by KunalS19** [comment]
> configuration project alternative for ios #84

Please help me, I am also getting the same error

**Comment by Akifcan** [comment]
I am getting same error only in ios
