### ISSUE TITLE
onDone callback not receiving any arguments

### ISSUE THREAD

**Issue by nbadag** [prscX/react-native-photo-editor#5]
From what I can tell from [this line](https://github.com/prscX/react-native-photo-editor/blob/master/RNPhotoEditor.js#L49), it seems like the `onDone` callback should be receiving a single argument (`path`) but I'm finding that it's always `undefined`.

Am I correct in thinking the `path` passed to `onDone` is supposed to be some form of uri for the manipulated image? My use case is one where rather than save the output of the editor to the camera roll, I need to pass it to a handler that saves it to a database. Is there a different/better way to access the manipulated image?

**Comment by prscX** [comment]
Thanks @nbadag for raising the query.

Currently in native itself the image is saved/updated at the same path post editing. `onDone` will not return any information. I have modified the same.

Thanks
</ Pranav >

**Comment by nbadag** [comment]
Exactly what I needed, thank you for the quick response! :)

**Comment by DavitVosk** [comment]
@nbadag can you please share some code? I don't understand how find the path of the changed image

**Comment by jcarlosjl** [comment]
Actually on iOS when saving the edited image it is stored in a different path. Does someone have the same problem?

**Comment by russelRajitha** [comment]
I have same issue, ondone giving path as undefined. any solution for this?
