### ISSUE TITLE
Install error (iOS)

### ISSUE THREAD

**Issue by yankovalera** [prscX/react-native-photo-editor#50]
Hi, I'm trying to install this module, but after checking that node_modules/react-native-photo-editor/ios/pods/Pods.xcodeproject is missing, when running "pod install" command on "node_modules/react-native-photo-editor/ios/" I'm getting this.

Installing iOSPhotoEditor (0.5)
[!] Unable to determine Swift version for the following pods:

- `iOSPhotoEditor` does not specify a Swift version and none of the targets (`RNPhotoEditor`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

Could you please help?

Regards

**Comment by prscX** [comment]
Thanks @yankovalera for raising the issue.

It is a know issue. I need to apply the fix to this library. Meantime please downgrade your pod version to 1.5 and below.

Thanks
</ Pranav >

**Comment by yankovalera** [comment]
thanks. Downgraded and was able to install it.

**Comment by prscX** [comment]
@yankovalera: The issue was fixed in latest pod version.

Could you please install latest `V1.*` and verify the same. Let me know incase you still face any issues.

Thanks
</ Pranav >
