### ISSUE TITLE
Photo editor is not opened when trying to open from opened modal

### ISSUE THREAD

**Issue by DavitVosk** [prscX/react-native-photo-editor#52]
I am using react-native-navigation. And there is an opened modal with `navigator.showModal`. On modal screen, there is a button which opens the phone media and the user chooses one image. After the image is chosen I want to open the photo editor to edit the picked image, but it does not do anything at all. Can you please help me to find a solution?

To note, it properly works on a normal screen, namely not from modal. Also I had tested with RN modal as well - in this case the photo editor is not opened again

**Comment by DavitVosk** [comment]
Some warning which I noticed on xcode which will help I hope:
`Warning: Attempt to present <iOSPhotoEditor.PhotoEditorViewController: 0x7feec100b600>  on <RCCTabBarController: 0x7feebe928200> which is already presenting <RCCNavigationController: 0x7feebd1a9e00>`

**Comment by DavitVosk** [comment]
@prscX could you please update for this issue?

**Comment by ssg-luke** [comment]
#63

**Comment by prscX** [comment]
Thanks @ssg-luke for sharing the PR and Effort.

@DavitVosk: Could you install latest version of library and migrate to RN61. Please  follow installation steps defined in `README`. Let me know incase you still face the same issue.

Thanks
</ Pranav >
