### ISSUE TITLE
Is CocoaPods really a dependency?

### ISSUE THREAD

**Issue by cristianoccazinsp** [prscX/react-native-photo-editor#53]
Title... Is it possible to set up the library on IOS without cocoa pods?

**Comment by prscX** [comment]
Thanks @cristianoccazinsp for raising the query.

RN61 and above we have deep integration with pods. I would recommend to migrate to RN61 and latest version of this library. 

Cocoa pods are required in other use native iOS dependencies.

Thanks
</ Pranav >
