### ISSUE TITLE
Gradle Assemble issue

### ISSUE THREAD

**Issue by yankovalera** [prscX/react-native-photo-editor#55]
Hi I'm trying to assemble a debug release but I'm getting the following error. Any ideas what could be happening?

> Task :react-native-photo-editor:processDebugAndroidTestResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-photo-editor:processDebugAndroidTestResources'.
> Android resource linking failed
  /Users/user/.gradle/caches/transforms-1/files-1.1/appcompat-v7-28.0.0.aar/dc160fa7acf9caeaba5bf6be7601c9e9/res/values-v28/values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.
      
  /Users/user/Development/ReactNative/reverapp/node_modules/react-native-photo-editor/android/build/intermediates/incremental/mergeDebugAndroidTestResources/merged.dir/values-v28/values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.
      
  /Users/user/.gradle/caches/transforms-1/files-1.1/design-27.1.1.aar/ab2ce60f82e542619b4f9d12c7dac434/res/values/values.xml:96:5-202: AAPT: error: resource android:attr/fontVariationSettings not found.
      
  /Users/user/.gradle/caches/transforms-1/files-1.1/design-27.1.1.aar/ab2ce60f82e542619b4f9d12c7dac434/res/values/values.xml:96:5-202: AAPT: error: resource android:attr/ttcIndex not found.
      
  error: failed linking references.

**Comment by cristianoccazinsp** [comment]
Most likely related to hardcoded gradle android sdk versions. Gradle file should look like this instead.

```
android {
        compileSdkVersion rootProject.ext.compileSdkVersion
        buildToolsVersion rootProject.ext.buildToolsVersion

        defaultConfig {
            minSdkVersion rootProject.ext.minSdkVersion
            targetSdkVersion rootProject.ext.targetSdkVersion
            versionCode 1
            versionName "1.0"
        }
        lintOptions {
            abortOnError false
        }
    }
```

**Comment by prscX** [comment]
Thanks @cristianoccazinsp for sharing the solution.

@yankovalera: Could you please install latest version and verify. Please upgrade to RN62 and follow installation steps for the same.

Let me know incase you still face the same issue.

Thanks
</ Pranav >

**Comment by cristianoccazinsp** [comment]
Thanks @prscX  for the updates. I've switched libraries a long time ago already, but will definitely give it a try if I need it again :)
