### ISSUE TITLE
Is it possible to load stickers from remote?

### ISSUE THREAD

**Issue by cactis** [prscX/react-native-photo-editor#59]
Hi, 

Too much stickers will increase app arcthive size, and if need to build a sticker markets, it will need to list stickers(set) form remote.

thanks.

**Comment by prscX** [comment]
Thanks @cactis for raising the query.

I am afraid to share that loading stickers from remote location is not supported, it has to be bundle with app assets.

Thanks
</ Pranav >

**Comment by lincolnsilva** [comment]
> Hi,
> 
> Too much stickers will increase app arcthive size, and if need to build a sticker markets, it will need to list stickers(set) form remote.
> 
> thanks.

You can change the RNPhotoEditor.m (iOS) file to display remote images like this:


Change:

for (NSString *sticker in stickers) {
            [imageStickers addObject: [UIImage imageNamed: sticker]];
}


to 


for (NSString *sticker in stickers) {
            //[imageStickers addObject: [UIImage imageNamed: sticker]];
            NSURL *url = [NSURL URLWithString:sticker];
            NSData *data = [NSData dataWithContentsOfURL:url];
            UIImage *img = [[UIImage alloc] initWithData:data];
            
            [imageStickers addObject:img];
}

and now use URLs in stickers paramerter array

*only for iOS.... have to do for Android
