### ISSUE TITLE
Ability to force crop to a specified aspect-ratio?

### ISSUE THREAD

**Issue by SnidelyWhiplash** [prscX/react-native-photo-editor#6]
Hi, thanks for this lib, it already looks great! I'm wondering if there's a way to pass in an aspect ratio directly? In our case we need to have photos set to `16:9`, and we need to disallow users from changing that.

Any thoughts?

**Comment by ejkkan** [comment]
any plans in implementing this?

**Comment by rendomnet** [comment]
Any updates on this?

**Comment by prscX** [comment]
Thanks @SnidelyWhiplash for raising the query.

This library is a wrapper around native libraries providing photo editing capabilities. Due to native libraries limitation, I am afraid to share that it is not possible at the moment. 

Please feel free to share PR for the same.

Thanks
</ Pranav >
