### ISSUE TITLE
 Stickers Page is empty in iOS

### ISSUE THREAD

**Issue by CrisHemswerthThor** [prscX/react-native-photo-editor#60]
I am getting an empty page of Stickers Page  in iOS ,and in case of android stickers are shown properly.

**versions:**
react-native: 0.59.3
react-native-photoeditor: 0.0.7

**Comment by Tyldar** [comment]
Have you added stickers in the xCode project as stated in the documentation?

**Comment by prscX** [comment]
Thanks @CrisHemswerthThor for raising the query.

Could you please add Stickers to your project Resources [ios/Resources]. Please refer Example project for the same. Let me know incase you still face same issue.

Thanks
</ Pranav >
