### ISSUE TITLE
Where i get manipulated image when done editing

### ISSUE THREAD

**Issue by babar7** [prscX/react-native-photo-editor#68]
Where i get manipulated image when onDone editing ? onDone callback not returns any source, url , path. I Have to show the manipulated image on the screen after done Editing, with uploading it again. If user does some mistake so that they can edit it again by clicking on icon.
![Simulator Screen Shot - iPhone 7 Plus - 2019-06-12 at 15 28 21](https://user-images.githubusercontent.com/26044457/59344118-da2a7500-8d26-11e9-8c1b-87ec61719b2a.png)
![Simulator Screen Shot - iPhone 7 Plus - 2019-06-12 at 15 29 03](https://user-images.githubusercontent.com/26044457/59344120-da2a7500-8d26-11e9-9b90-62aca51bea95.png)

projectResponse = this.props.projectResponse;
  item = this.props.navigation.state.params.item;
 
  state = {
    annotation: '',
    imageSource : Images.icAddImage,
    scroll  : true
  };

  componentDidMount() {
   
    this.props.getTagList();
    this.uploadImage();
  };

  editImage = () => {
    RNPhotoEditor.Edit({
      path: this.state.imageSource.uri,
      hiddenControls : ["sticker" , "share"],
      onDone : () => {
        this.setState({
          imageSource : this.state.imageSource
        }, () => {
          console.log("OnDone", this.state.imageSource);

        })
      },
      onCancel : (res) => {
      console.log("onCancelEditing", res);
      }
      // onDone : this.onDoneEditing,
      // onCancel : this.onCancelEditing
  });
  }

**Comment by prscX** [comment]
@babar7: it modify and save the image at the same location.

Thanks
</ Pranav >

**Comment by fpintaric** [comment]
It would be much more useful if the onDone callback provided the new path of the image instead of just saving it in gallery under an unknown name.

**Comment by babakansari** [comment]
Not sure why the following code is not saving the modified image?

`RNPhotoEditor.Edit({
        path: '/storage/emulated/0/Pictures/Bob.png',
        stickers: [
          'sticker0',
          'sticker1',
          'sticker2',
          'sticker3',
          'sticker4',
          'sticker5',
          'sticker6',
          'sticker7',
          'sticker8',
          'sticker9',
          'sticker10',
        ],
        hiddenControls: ["sticker" , "share"],
        colors: [colors.TOMATO_RED_1, colors.GREEN_APPLE_1, colors.BRIGHT_BLUE_2],
        onDone: (args) => {
          // console.log('on done');
        },
        onCancel: (args) => {
          // console.log('on cancel');
        },
      });`

**Comment by AmmarAshfaq** [comment]
> @babar7: it modify and save the image at the same location.
> 
> Thanks
> </ Pranav >

it doesn't save in the same location after edit and better if onDone method return URL

**Comment by babakansari** [comment]
It saves in a folder with different file names and save the same Image with the right arrow key!
