### ISSUE TITLE
I have following error on run time

### ISSUE THREAD

**Issue by sachinbasendr** [prscX/react-native-photo-editor#69]
Could not find com.github.prscX:photo-editor-android:master-SNAPSHOT.
  Searched in the following locations:
    - file:/home/user/Android/Sdk/extras/m2repository/com/github/prscX/photo-editor-android/master-SNAPSHOT/maven-metadata.xml
    - file:/home/user/Android/Sdk/extras/m2repository/com/github/prscX/photo-editor-android/master-SNAPSHOT/photo-editor-android-master-SNAPSHOT.pom
    - file:/home/user/Android/Sdk/extras/m2repository/com/github/prscX/photo-editor-android/master-SNAPSHOT/photo-editor-android-master-SNAPSHOT.jar
    - file:/home/user/Android/Sdk/extras/google/m2repository/com/github/prscX/photo-editor-android/master-SNAPSHOT/maven-metadata.xml
    - file:/home/user/Android/Sdk/extras/google/m2repository/com/github/prscX/photo-editor-android/master-SNAPSHOT/photo-editor-android-master-SNAPSHOT.pom
    - file:/home/user/Android/Sdk/extras/google/m2repository/com/github/prscX/photo-editor-android/master-SNAPSHOT/photo-editor-android-master-SNAPSHOT.jar
    - file:/home/user/Android/Sdk/extras/android/m2repository/com/github/prscX/photo-editor-android/master-SNAPSHOT/maven-metadata.xml
    - file:/home/user/Android/Sdk/extras/android/m2repository/com/github/prscX/photo-editor-android/master-SNAPSHOT/photo-editor-android-master-SNAPSHOT.pom
    - file:/home/user/Android/Sdk/extras/android/m2repository/com/github/prscX/photo-editor-android/master-SNAPSHOT/photo-editor-android-master-SNAPSHOT.jar
    - file:/root/.m2/repository/com/github/prscX/photo-editor-android/master-SNAPSHOT/maven-metadata.xml
    - file:/root/.m2/repository/com/github/prscX/photo-editor-android/master-SNAPSHOT/photo-editor-android-master-SNAPSHOT.pom
    - file:/root/.m2/repository/com/github/prscX/photo-editor-android/master-SNAPSHOT/photo-editor-android-master-SNAPSHOT.jar
    - https://dl.google.com/dl/android/maven2/com/github/prscX/photo-editor-android/master-SNAPSHOT/maven-metadata.xml
    - https://dl.google.com/dl/android/maven2/com/github/prscX/photo-editor-android/master-SNAPSHOT/photo-editor-android-master-SNAPSHOT.pom
    - https://dl.google.com/dl/android/maven2/com/github/prscX/photo-editor-android/master-SNAPSHOT/photo-editor-android-master-SNAPSHOT.jar
    - https://jcenter.bintray.com/com/github/prscX/photo-editor-android/master-SNAPSHOT/maven-metadata.xml
    - https://jcenter.bintray.com/com/github/prscX/photo-editor-android/master-SNAPSHOT/photo-editor-android-master-SNAPSHOT.pom
    - https://jcenter.bintray.com/com/github/prscX/photo-editor-android/master-SNAPSHOT/photo-editor-android-master-SNAPSHOT.jar
    - file:/home/user/Documents/react/imageSb/node_modules/react-native/android/com/github/prscX/photo-editor-android/master-SNAPSHOT/maven-metadata.xml
    - file:/home/user/Documents/react/imageSb/node_modules/react-native/android/com/github/prscX/photo-editor-android/master-SNAPSHOT/photo-editor-android-master-SNAPSHOT.pom
    - file:/home/user/Documents/react/imageSb/node_modules/react-native/android/com/github/prscX/photo-editor-android/master-SNAPSHOT/photo-editor-android-master-SNAPSHOT.jar
  Required by:
      project :app > project :react-native-photo-editor

**Comment by prscX** [comment]
Thanks @sachinbasendr for raising the issue.

Could you please share software stack and have you added below statement to your android app gradle:


```
buildscript {
    repositories {
        maven { url "https://jitpack.io" }
        ...
    }
}

allprojects {
    repositories {
        maven { url "https://jitpack.io" }
        ...
    }
}
```


Thanks
</ Pranav >
