### ISSUE TITLE
iPhoneX SafeArea support

### ISSUE THREAD

**Issue by SnidelyWhiplash** [prscX/react-native-photo-editor#7]
At the moment, it appears the library is not accounting for iPhoneX display size. Please see attached screenshot. The icons up top are really hard to access, and the ones on the bottom are too close to the swipe-to-dismiss bar.

I _think_ wrapping everything in a `<SafeAreaView>` should fix it.

![img_2841](https://user-images.githubusercontent.com/6245069/45899370-7e335100-bd91-11e8-9b39-9fcc8a54cbc4.PNG)

**Comment by prscX** [comment]
Hi @SnidelyWhiplash + @srameshr + @bra-shelker: I have fix the layout issues w.r.t iPhoneX.

Can you please install latest version and verify the same. Please let me know incase you face any issues.

Thanks
</ Pranav >

**Comment by ddereszewski** [comment]
It's good 
![screen shot 2018-09-28 at 09 29 12](https://user-images.githubusercontent.com/2223591/46194195-fe613580-c300-11e8-83ba-b808f05cfbb3.png)
