### ISSUE TITLE
Cannot disable emoji stickers ?

### ISSUE THREAD

**Issue by RDardelet** [prscX/react-native-photo-editor#75]
Is there no way to disable the emoji stickers ?

I wish to make an app with only some specific stickers, and so far the first page of the stickers picker only shows my custom pickers, but I can't figure out how to disable the second page, with the emoji

**Comment by shiva5538** [comment]
Hi, You achieved this? If yes, please let me know how. Thanks in adv.

**Comment by prscX** [comment]
Thanks @RDardelet for raising query.

I am afraid but disabling sticker feature is not supported by the native library we have integrated for the photo editing.

Thanks
</ Pranav >

**Comment by hamzaouhssain1993** [comment]
you should go to the native part of the two libraries and disable it from there as prscX said
