### ISSUE TITLE
Http url not opening in android

### ISSUE THREAD

**Issue by babar7** [prscX/react-native-photo-editor#81]
on ios works perfect
http://360cubes.com/field_scope_staging/public/uploads/media/1566460450189-1566460492-394165210.jpg

it goes black and after edit on done it returns black edited image,
 

![Screenshot_1567423917](https://user-images.githubusercontent.com/26044457/64111891-35f12100-cd9f-11e9-8ef0-8ef5af3cb5f4.png)
![Screenshot_1567423921](https://user-images.githubusercontent.com/26044457/64111892-3689b780-cd9f-11e9-80f8-3747a52c605b.png)

**Comment by RZulfikri** [comment]
@babar7 check my latest code. https://github.com/RZulfikri/react-native-photo-editor/tree/fix/detect-orientation. Or try to change this line https://github.com/RZulfikri/react-native-photo-editor/commit/8ee6a6b991d0fc605d4b1f255a089c372bf88270

**Comment by babar7** [comment]
@RZulfikri  Thanks for your quick response, 
I tried both, but the response is still same, 

Here is my sample of code :

editImage = () => {
    let imgPath = "http://360cubes.com/field_scope_staging/public/uploads/media/1566460450189-1566460492-394165210.jpg";
    RNPhotoEditor.Edit({
      path: imgPath,
      hiddenControls: ["sticker", "share"],
      onDone: this.onDoneEditing,
      onCancel: this.onCancelEditing
    });
  };

onDoneEditing = (response) => {
 console.log("Edited Image path :", response)
}
I pass the http url in path but editor goes black and shows black image

**Comment by RZulfikri** [comment]
hmm, I think you need to save your file to local first as temporary file, instead of directly pass it to editor.

**Comment by babar7** [comment]
Is there any possibility to convert url to uri , without saving into local ?

**Comment by babar7** [comment]
Also the  crop feature is not support in android ? and one other thing is that after markup if I try to write some text is clears the markup

**Comment by raginisahu** [comment]
Did you find any solution ?
please help me out

**Comment by babar7** [comment]
@raginisahu The only solution is to save the file to local as tem file , then pas the uri, Im using the RNFetchBlob for this, 
let urlToFetch = imageSource.url
      RNFetchBlob
        .config({
          fileCache: true,
          appendExt: 'jpg'
        })
        .fetch('GET', urlToFetch, {
          //some headers ..
        })
        .then((res) => {
          // the temp file path with file extension `jpg`
          console.log('The file saved to ', res.path());
          imgPath = res.path();
          this.editImage(imgPath);
        }) 
may this helps you.
