### ISSUE TITLE
Separate functions for every editing options

### ISSUE THREAD

**Issue by MohdSaleh** [prscX/react-native-photo-editor#82]
How to make every function with different options, so it will be easy to customise the editor looks completely and also it is possible to use react as its frontend.

**Comment by prscX** [comment]
Thanks @MohdSaleh for raising the query.

This library is RN wrapper around native libraries providing capability for editing photo. I am afraid to share that it is bit difficult to customize it through React wrapper and moreover these native libraries does not have capability for custom UI/UX.

Thanks
</ Prana v>
