### ISSUE TITLE
Video Support

### ISSUE THREAD

**Issue by BaderSerhan** [prscX/react-native-photo-editor#83]
Hello and thanks for the great effort in this library!

I want to build a photo and video editor in my app (similar to apps like Instagram and TikTok), but I am finding the editor libraries in react-native are very scarce, especially for video. I would like to be able to add text, gifs, effects, filters... to videos and then save/upload them to the server.
Thus, are you planning to support videos in this library? I noticed that [this swift library which is based on eventtus library as well](https://github.com/FarisAlbalawi/PhotoVideoEditor) is somehow supporting video, though I don't know-how.

Any help is appreciated, thank you.

**Comment by prscX** [comment]
Thanks @BaderSerhan for raising query.

I am afraid to share but Video editing is not in scope. It is not supported by native library we are using for photo editing. This library is simply a wrap around native available library for photo editing.

Do you know any native Android/iOS library for video editing?

Thanks
</ Pranav >

**Comment by BaderSerhan** [comment]
Thanks for your reply.

> 
> Do you know any native Android/iOS library for video editing?
> 

I came across these two iOS libraries while doing my research, but I don't know much about their capabilities.

https://github.com/burhanrashid52/PhotoEditor
https://github.com/FarisAlbalawi/PhotoVideoEditor

**Comment by prscX** [comment]
Thanks @BaderSerhan for sharing native libraries for Video editing.

- [burhanrashid52/PhotoEditor](https://github.com/burhanrashid52/PhotoEditor): As per my understanding, it does not have support video editing capabilities.

- [FarisAlbalawi/PhotoVideoEditor](https://github.com/FarisAlbalawi/PhotoVideoEditor):  I will perform background checks on this library. It might take some time.

If I came across any such libraries will share the same.

Thanks
</ Pranav >
