### ISSUE TITLE
configuration project alternative for ios

### ISSUE THREAD

**Issue by luifer94** [prscX/react-native-photo-editor#84]
I am new on RN I have no experience on iOS, so when triying to install the library for IOS I got the message: "coudnt inspect application package" and that problem was solved by removing iOSPhotoEditor.framework from Embedded Binaries BUT another problems starts appearing similar to this: https://github.com/prscX/react-native-photo-editor/issues/25#issuecomment-441148106

So what I did was:
1) react-native link react-native-photo-editor
2) go to node_modules/react-native-photo-editor/ios/ and pod repo update and pod install
3) Add(with "create groups" and "copy items if needed" options) Pods.xcodeproject and RNPhotoEditor.xcodeproject to Pod Folder as this:
Pods
      RNPHOTOEDITOR
            Pods.xcodeproject
            RNPhotoEditor.xcodeproject 
4) Build Settings -> Frameworks Search Path add : ${PODS_ROOT}/iOSPhotoEditor non recursive for debug and release
5)  add values to:  info.list as docs suggest

and seems that is working but not sure if It is ok or If It will have problems on future.

**Comment by luifer94** [comment]
Got the next message: https://github.com/prscX/react-native-photo-editor/issues/49

**Comment by shiva5538** [comment]
@luifer94 , can you please explain step no: 3 in detail.

**Comment by eugenepla** [comment]
@luifer94 There is no Podfile anymore in ios dir
is there an updated guide on how to connect?

**Comment by prscX** [comment]
Thanks @luifer94 for raising the query.

Could you please try by migrate your app to RN61 and upgrade library to `V1.*`. Let me know in case it . does not work.

Thanks
</ Pranav >
