### ISSUE TITLE
android build fail

### ISSUE THREAD

**Issue by maherzaidoune** [prscX/react-native-photo-editor#85]
hey, first of all, thank you for sharing this awesome library with the community.
i tried to build my project after adding react-native-photo-editor and it fail, your example fail to build too, i got this error : 

* What went wrong:
A problem occurred configuring root project 'Example'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.bouncycastle:bcprov-jdk15on:1.56.
     Required by:
         project : > com.android.tools.build:gradle:3.2.1 > com.android.tools.build:builder:3.2.1
         project : > com.android.tools.build:gradle:3.2.1 > com.android.tools.build:builder:3.2.1 > com.android.tools:sdk-common:26.2.1
         project : > com.android.tools.build:gradle:3.2.1 > com.android.tools.build:builder:3.2.1 > com.android.tools.build:apkzlib:3.2.1
         project : > com.android.tools.build:gradle:3.2.1 > com.android.tools.build:builder:3.2.1 > org.bouncycastle:bcpkix-jdk15on:1.56
      > Could not resolve org.bouncycastle:bcprov-jdk15on:1.56.
         > Could not get resource 'https://jitpack.io/org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56.pom'.
            > Could not HEAD 'https://jitpack.io/org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56.pom'. Received status code 522 from server: Origin Connection Time-out

i didn't see any issue about this here , am i the only one facing this problem ?

**Comment by NathanOelke** [comment]
I am experiencing this same problem as well.

**Comment by sblondell** [comment]
Try this.
Go to the build.gradle of the react-native-photo-editor in your node_modules folder.

node_modules > react-native-photo-editor > android > build.gradle

make sure the "maven { url 'https://jitpack.io' }" entry is the last entry in the repositories list
