### ISSUE TITLE
Obsolete iOS guide

### ISSUE THREAD

**Issue by eugenepla** [prscX/react-native-photo-editor#86]
Current guide on how to connect iOS is obsolete
https://github.com/prscX/react-native-photo-editor#-getting-started

There is no Podfile anymore in ios dir
is there an updated guide on how to connect iOS?

**Comment by prscX** [comment]
Thanks @eugenepla for raising query.

> = `V1` we have different section for installation steps and you need to migrate your project to RN61 >= will have `Podfile`. Please refer `README`. 

Thanks
</ Pranav >
