### ISSUE TITLE
Editor is on swipe-to-dismiss modal on iOS 13 

### ISSUE THREAD

**Issue by milansusnjar** [prscX/react-native-photo-editor#87]
On iOS 13 editor is on swipe-to-dismiss modal and we cannot draw line, it is trying to swipe modal down.

![qaoIQfjaeJ](https://user-images.githubusercontent.com/19948979/66162357-7b1ea200-e62e-11e9-9375-ba029507f355.gif)

**Comment by karn18** [comment]
ios 13, default modal presenting is page sheet. Not fullscreen like ios 12

I add this code in RNPhotoEditor.m, to fullscreen the modal

```
// The default modal presenting is page sheet in ios 13, not full screen
if (@available(iOS 13, *)) {
   [photoEditor setModalPresentationStyle: UIModalPresentationFullScreen];
}
```
