### ISSUE TITLE
OnCancel doesn't trigger when close the editor

### ISSUE THREAD

**Issue by ddereszewski** [prscX/react-native-photo-editor#9]
When clicking Close onClose doesn't trigger

**Comment by prscX** [comment]
Thanks @ddereszewski for raising the issue. 

I have made the required fix and push a release with the same. Can you please install latest version and verify the same.

Please let me know incase you face any issues.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @ddereszewski: My Bad. I have pushed the release on npm.

Can you please verify the same. Please let me know incase you face any issues.

Thanks
</ Pranav >
