### ISSUE TITLE
How to edit and add texts programmatically?

### ISSUE THREAD

**Issue by codelayerorg** [prscX/react-native-photo-editor#90]
Sorry if this space is not for that. I'm not figuring out how to edit previously added texts, is it possible? Also... Is it possible to load an image, adding programmatically predefined texts (without user interation, but which should be possible to edit by user later)?

**Comment by prscX** [comment]
Thanks @codelayerorg for raising query.

I am afraid to share above requested features are not supported.

Thanks
</ Pranav >
