### ISSUE TITLE
[iOS] Compile Swift failed

### ISSUE THREAD

**Issue by hieupaul** [prscX/react-native-photo-editor#91]
Hi, I have an issue when build project: 

**BUILD FAILED**
CompileSwift normal arm64
'keyboardAnimationDurationUserInfoKey' has been renamed to 'UIKeyboardAnimationCurveUserInfoKey'
...

I see it change in your commit [- swift 5 support](https://github.com/prscX/photo-editor/commit/4924e9ec984d25d03644e58aa148282642171de9#diff-ad0f4c51a1b36c41e74e4e23b1786c6b) ??

Version:
RN 0.59.8
RNPE 0.0.7

Thanks

**Comment by guoliang1206** [comment]
same issue when update react-native to 0.60.0

**Comment by vinpro24** [comment]
Same issue? Any idea, pls

**Comment by Alek-devsy** [comment]
I have the same issue. 
xcode 11.1 
RN 0.59.9
RNPE 0.0.7
I got a bunch of errors like this (only from this library)

**Comment by DaveLomber** [comment]
Same here
I got 100 errors when upgraded the lib from 0.7.0 => 1.0.0

**Comment by prscX** [comment]
Thanks @hieupaul for raising the issue. Could you please try again by adding below statement to your app `Podfile`:

```
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name.include?('iOSPhotoEditor')
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '5'
        end
      end
    end
  end
```

P.S: Also please upgrade RN to 61 and try since it has a better support for `use_frameworks!`

Thanks
</ Pranav >

**Comment by nwaughachukwuma** [comment]
Hi @prscX I tried this on RN61.5 but I couldn't get it to work.
