### ISSUE TITLE
react-native-photo-editor not work with Cameraroll 

### ISSUE THREAD

**Issue by DarkbaronHUST** [prscX/react-native-photo-editor#94]
I'm new with react! please help !

I'm using @react-native-community/cameraroll to get information of photo, then edit photo by react-native-photo-editor on iOS.

But the photo's uri return from @react-native-community/cameraroll 
(ph://ED7AC36B-A150-4C38-BB8C-B6D696F4F2ED/L0/001) does not compatible with the  path Props of react-native-photo-editor,. Then MyApp crash.
I'm trying to get another fomat of photo's uri by using CameraRoll.getSeclectedPhoto (also belong to @react-native-community/cameraroll) then got the filepath (file://............./data/Media/DCIM/.../IMG_008.JPG). This filepath still also not compatible :( When Edit Photo, I got Error form xCode show : "Whose view is not in the window hierarchy".

But When i'm using react-native-community/react-native-image-picker with react-native-photo-editor, it's work perfect, With same photo, The photo's uri from react-native-image-picker is also start with file://...........
but different in detail with photo's uri got from@react-native-community/cameraroll. 

is there any way to use react-native-photo-editor with Cameraroll ! 
Please help me! 
Thanks

**Comment by prscX** [comment]
Thanks @DarkbaronHUST for raising the issue.

This library supports editing photos which are within app sandbox. You need to move captured file to app sandbox then use that path with this library.

Let me know in case it does not works

Thanks
</ Pranav >
