### ISSUE TITLE
Hidden controls doesn't work on iOS

### ISSUE THREAD

**Issue by maxmijn** [prscX/react-native-photo-editor#96]
When I add the following (or any other) hidden controls to the photo editor, the controls are hidden on Android but not on iOS.

```
hiddenControls: ['crop', 'save', 'share']
```

**Comment by maxmijn** [comment]
https://github.com/prscX/react-native-photo-editor/blob/c5e7e608a51d84ae735f875a1b79634707d38133/ios/RNPhotoEditor.m#L83

is commented out. When uncommenting, the controls are hidden. Was this commented for a reason?

**Comment by maxmijn** [comment]
https://github.com/prscX/react-native-photo-editor/pull/97

**Comment by prscX** [comment]
Thanks @maxmijn for the PR. I have pushed the release.

You can now disable controls based on your need.

Thanks
</ Pranav >
